# NetlifyCMS config file
# https://www.netlifycms.org/docs/configuration-options/

backend:
  # Use Netlify Identity as backend
  name: git-gateway
  branch: main
media_folder: "src/assets/media"
public_folder: "/assets/media"
logo_url: "/assets/img/hestialabs-logo.svg"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
publish_mode: editorial_workflow
display_url: /en/

i18n:
  # Required and can be one of multiple_folders, multiple_files or single_file
  # multiple_folders - persists files in `<folder>/<locale>/<slug>.<extension>`
  # multiple_files - persists files in `<folder>/<slug>.<locale>.<extension>`
  # single_file - persists a single file in `<folder>/<slug>.<extension>`
  structure: multiple_folders

  # Required - a list of locales to show in the editor UI
  locales: [en, fr]

  # Optional, defaults to the first item in locales.
  # The locale to be used for fields validation and as a baseline for the entry.
  default_locale: en

collections:
- label: ‹Dictionary i18n›
  name: i18n-fragments
  i18n:
    structure: single_file
  files:
    - label: Global text fragments
      name: i18n-globals
      file: src/site/_data/i18n/globals.json
      i18n: true
      fields:
        - { label: Suggested blog posts, name: suggested_posts_title, required: false, i18n: true,
            widget: markdown, buttons: [bold, italic, link], editor_components: [], minimal: true }
        - { label: Share, name: share, required: false, widget: string, i18n: true }
        - { label: Read more ‹button›, name: read_more, required: false, widget: string, i18n: true }
        - { label: Ask for your data ‹button›, name: ask_your_data, required: false, widget: string, i18n: true }
        - { label: By (author), name: by_author, required: false, widget: string, i18n: true }
        - { label: Published on, name: published_on, required: false, widget: string, i18n: true }
    - label: Header and footer text fragments
      name: i18n-header-footer
      file: src/site/_data/i18n/header_footer.json
      i18n: true
      fields:
        - { label: Home, name: home, required: false, widget: string, i18n: true }
        - { label: Expertise, name: expertise, required: false, widget: string, i18n: true }
        - { label: Use cases, name: usecases, required: false, widget: string, i18n: true }
        - { label: Legal, name: legal, required: false, widget: string, i18n: true }
        - { label: About, name: about, required: false, widget: string, i18n: true }
    - label: Components text fragments (newsletter, contact and sar forms)
      name: i18n-newsletter-signup
      file: src/site/_data/i18n/assets/component-translations.json
      i18n: true
      fields:
        - { label: "Contact form > First name", name: contact-form-first_name, required: false, widget: string, i18n: true }
        - { label: "Contact form > Last name", name: contact-form-last_name, required: false, widget: string, i18n: true }
        - { label: "Contact form > E-mail address", name: contact-form-email, required: false, widget: string, i18n: true }
        - { label: "Contact form > Subject", name: contact-form-subject, required: false, widget: string, i18n: true }
        - { label: "Contact form > Message", name: contact-form-message, required: false, widget: string, i18n: true }
        - { label: "Contact form > Submit button", name: contact-form-submit_button, required: false, widget: string, i18n: true }
- label: ‹Configuration›
  name: configuration
  files:
    - label: External links
      name: links
      file: src/site/_data/links.json
      i18n: false
      fields:
        - { label: Base url of the website, name: canonical_base_url, required: false, widget: string,
            hint: "Without https://" }
        - { label: Twitter label, name: twitter_label, required: false, widget: string,
            hint: "If this field is empty, the link to twitter will not appear in the website's footer" }
        - { label: Twitter URL, name: twitter_url, required: true, widget: string }
        - { label: Forum label, name: forum_label, required: false, widget: string ,
            hint: "If this field is empty, the link to the forum will not appear in the website's footer" }
        - { label: Forum URL, name: forum_url, required: true, widget: string }
        - label: "Additional links"
          name: "additional_links"
          widget: "list"
          summary: '{{fields.name}}'
          fields:
            - {label: Name, name: name, widget: string }
            - {label: Link, name: url, widget: file}

- label: Home page
  name: home
  # Configure i18n for this collection.
  folder: src/site/home
  extension: md
  editor:
    preview: false
  create: false
  delete: false
  i18n:
    structure: multiple_folders
  preview_path: /en/
  fields:
    - { label: "Browser tab title", name: title, required: false, widget: string, i18n: true }
    - { label: Lead , name: lead, required: false, widget: markdown, i18n: true }
    - { label: Lead image , name: lead_image, required: false, widget: image, i18n: true }
    - { label: "Lead image caption", name: lead_image_caption, required: false, i18n: true,
        widget: markdown, buttons: [bold, italic, link], editor_components: [], minimal: true }
    - { label: "Introduction title", name: introduction_title, required: false, i18n: true,
        widget: markdown, buttons: [bold, italic, link], editor_components: [], minimal: true}
    - { label: Introduction , name: introduction, required: false, widget: markdown, i18n: true }
    - label: "Expertise"
      name: "expertise"
      widget: "list"
      summary: '{{fields.title}}'
      i18n: true
      fields:
        - { label: "Title", name: title, required: false, i18n: true,
            widget: markdown, buttons: [bold, italic, link], editor_components: [], minimal: true}
        - { label: "Description", name: description, required: false, widget: markdown, i18n: true }
        - { label: "Link text", name: link_text, required: false, widget: string, i18n: true }
        - { label: Link, name: url, required: false, widget: file, i18n: true,
            hint: 'Write a relative url if you link to another page on this website. (for example "partners/", not "/partners/")'}
        - { label: "Colored button", name: primary_button, required: false, widget: boolean, i18n: true }
    - { label: "Realizations title", name: realizations_title, required: false, i18n: true,
        widget: markdown, buttons: [bold, italic, link], editor_components: [], minimal: true}
    - label: "Realizations"
      name: "realizations"
      widget: "list"
      summary: '{{fields.title}}'
      i18n: true
      fields:
        - { label: "Title", name: title, required: false, i18n: true,
            widget: markdown, buttons: [bold, italic, link], editor_components: [], minimal: true}
        - { label: "Description", name: description, required: false, widget: markdown, i18n: true }
        - { label: "Link text", name: link_text, required: false, widget: string, i18n: true }
        - { label: Link, name: url, required: false, widget: file, i18n: true,
            hint: 'Write a relative url if you link to another page on this website. (for example "partners/", not "/partners/")'}
        - { label: "Colored button", name: primary_button, required: false, widget: boolean, i18n: true }


    - { label: "Contact form title", name: contact_form_title, required: false, i18n: true,
        widget: markdown, buttons: [bold, italic, link], editor_components: [], minimal: true}
- label: About
  name: about
  folder: src/site/about
  extension: md
  editor:
    preview: false
  create: false
  delete: false
  i18n: true
  preview_path: /en/about/
  fields:
    - { label: "Browser tab title", name: title, required: false, widget: string, i18n: true }
    - { label: Lead , name: lead, required: false, widget: markdown, i18n: true }
    - { label: Lead image , name: lead_image, required: false, widget: image, i18n: true }
    - { label: "Lead image caption", name: lead_image_caption, required: false, i18n: true,
        widget: markdown, buttons: [bold, italic, link], editor_components: [], minimal: true }
    - { label: "Story title", name: story_title, required: false, i18n: true,
        widget: markdown, buttons: [bold, italic, link], editor_components: [], minimal: true}
    - { label: "Story", name: story, required: false, widget: markdown, i18n: true }
    - label: "People"
      name: "people"
      widget: "list"
      i18n: true
      summary: '{{fields.name}}'
      fields:
        - { label: Name, name: name, required: false, widget: string }
        - { label: Description, name: description, required: false, widget: markdown }
        - { label: Image, name: image, required: false, widget: image }
        - { label: Twitter, name: twitter, required: false, widget: string }
        - { label: Linkedin, name: linkedin, required: false, widget: string }
        - { label: E-mail, name: email, required: false, widget: string }
    - { label: "Philosophy title", name: philosophy_title, required: false, i18n: true,
        widget: markdown, buttons: [bold, italic, link], editor_components: [], minimal: true}
    - { label: "Philosophy", name: philosophy, required: false, widget: markdown, i18n: true }
- label: Legal
  name: legal
  folder: src/site/legal
  extension: md
  editor:
    preview: false
  create: false
  delete: false
  i18n: true
  preview_path: /en/legal/
  fields:
    - { label: "Browser tab title", name: title, required: false, widget: string, i18n: true }
    - { label: Lead, name: lead, required: false, i18n: true,
        widget: markdown, buttons: [bold, italic, link], editor_components: [], minimal: true }
    - { label: Body, name: body, required: false, widget: markdown, i18n: true }

# eof
